# apiVersion: v1
# kind: Service
# metadata:
#   name: web-svc
#   namespace: default
#   labels:
#     app: weblog
#     type: frontend
# spec:
#   selector:
#     app: weblog
#     type: frontend
#   ports:
#   - port: 80
#     targetPort: 80

## using nodePort because docker vm could not use ingress addon...
apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: default
  labels:
    app: weblog
    type: frontend
spec:
  type: NodePort
  selector:
    app: weblog
    type: frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
