apiVersion: v1
kind: Service
metadata:
  name: db-svc
  namespace: default
  labels:
    app: weblog
    type: database
spec:
  selector:
    app: weblog
    type: database
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None

