apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-volume-0
  namespace: default
  labels:
    app: weblog
    type: storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: slow
  hostPath:
    path: "/home/docker/webApp/storage/pv000"
    type: Directory

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-volume-1
  namespace: default
  labels:
    app: weblog
    type: storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: slow
  hostPath:
    path: "/home/docker/webApp/storage/pv001"
    type: Directory

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-volume-2
  namespace: default
  labels:
    app: weblog
    type: storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: slow
  hostPath:
    path: "/home/docker/webApp/storage/pv002"
    type: Directory

# ---

# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: storage-volume
#   namespace: default
#   labels:
#     app: weblog
#     type: storage
# spec:
#   capacity:
#     storage: 1Gi
#   # volumeMode: Filesystem
#   accessModes:
#     - ReadWriteMany
#   # persistentVolumeReclaimPolicy: Recycle
#   storageClassName: slow
#   hostPath:
#     # path: "/data/storage"
#     path: "/home/docker/webApp/storage/pv000"
#     type: Directory
#   # mountOptions:
#   #   - hard
#   #   - nfsvers=4.1
#   # nfs:
#   #   path: /tmp
#   #   server: 172.17.0.2

# ---

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: storage-claim
#   labels:
#     app: weblog
#     type: storage
# spec:
#   resources:
#     requests:
#       storage: 1Gi
#   # volumeMode: Filesystem
#   accessModes:
#     - ReadWriteMany
#   storageClassName: slow
